/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as BroadcastsIndexRouteImport } from './routes/broadcasts/index'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as CampaignsIdRouteImport } from './routes/campaigns/$id'
import { Route as BroadcastsNewRouteImport } from './routes/broadcasts/new'
import { Route as BroadcastsIdRouteImport } from './routes/broadcasts/$id'
import { Route as CampaignsIdIndexRouteImport } from './routes/campaigns/$id/index'
import { Route as BroadcastsIdIndexRouteImport } from './routes/broadcasts/$id/index'
import { Route as BroadcastsIdReportRouteImport } from './routes/broadcasts/$id/report'
import { Route as BroadcastsIdEditRouteImport } from './routes/broadcasts/$id/edit'
import { Route as ApiMarketingUnsubscribeRouteImport } from './routes/api/marketing/unsubscribe'
import { Route as ApiMarketingSendCampaignRouteImport } from './routes/api/marketing/send-campaign'
import { Route as ApiAutomationsEnrollRouteImport } from './routes/api/automations/enroll'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastsIndexRoute = BroadcastsIndexRouteImport.update({
  id: '/broadcasts/',
  path: '/broadcasts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastsNewRoute = BroadcastsNewRouteImport.update({
  id: '/broadcasts/new',
  path: '/broadcasts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastsIdRoute = BroadcastsIdRouteImport.update({
  id: '/broadcasts/$id',
  path: '/broadcasts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdIndexRoute = CampaignsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsIdRoute,
} as any)
const BroadcastsIdIndexRoute = BroadcastsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BroadcastsIdRoute,
} as any)
const BroadcastsIdReportRoute = BroadcastsIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => BroadcastsIdRoute,
} as any)
const BroadcastsIdEditRoute = BroadcastsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BroadcastsIdRoute,
} as any)
const ApiMarketingUnsubscribeRoute = ApiMarketingUnsubscribeRouteImport.update({
  id: '/api/marketing/unsubscribe',
  path: '/api/marketing/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingSendCampaignRoute =
  ApiMarketingSendCampaignRouteImport.update({
    id: '/api/marketing/send-campaign',
    path: '/api/marketing/send-campaign',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAutomationsEnrollRoute = ApiAutomationsEnrollRouteImport.update({
  id: '/api/automations/enroll',
  path: '/api/automations/enroll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/broadcasts/$id': typeof BroadcastsIdRouteWithChildren
  '/broadcasts/new': typeof BroadcastsNewRoute
  '/campaigns/$id': typeof CampaignsIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/broadcasts/': typeof BroadcastsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/api/automations/enroll': typeof ApiAutomationsEnrollRoute
  '/api/marketing/send-campaign': typeof ApiMarketingSendCampaignRoute
  '/api/marketing/unsubscribe': typeof ApiMarketingUnsubscribeRoute
  '/broadcasts/$id/edit': typeof BroadcastsIdEditRoute
  '/broadcasts/$id/report': typeof BroadcastsIdReportRoute
  '/broadcasts/$id/': typeof BroadcastsIdIndexRoute
  '/campaigns/$id/': typeof CampaignsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/broadcasts/new': typeof BroadcastsNewRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/broadcasts': typeof BroadcastsIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/team': typeof TeamIndexRoute
  '/api/automations/enroll': typeof ApiAutomationsEnrollRoute
  '/api/marketing/send-campaign': typeof ApiMarketingSendCampaignRoute
  '/api/marketing/unsubscribe': typeof ApiMarketingUnsubscribeRoute
  '/broadcasts/$id/edit': typeof BroadcastsIdEditRoute
  '/broadcasts/$id/report': typeof BroadcastsIdReportRoute
  '/broadcasts/$id': typeof BroadcastsIdIndexRoute
  '/campaigns/$id': typeof CampaignsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/broadcasts/$id': typeof BroadcastsIdRouteWithChildren
  '/broadcasts/new': typeof BroadcastsNewRoute
  '/campaigns/$id': typeof CampaignsIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/broadcasts/': typeof BroadcastsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/api/automations/enroll': typeof ApiAutomationsEnrollRoute
  '/api/marketing/send-campaign': typeof ApiMarketingSendCampaignRoute
  '/api/marketing/unsubscribe': typeof ApiMarketingUnsubscribeRoute
  '/broadcasts/$id/edit': typeof BroadcastsIdEditRoute
  '/broadcasts/$id/report': typeof BroadcastsIdReportRoute
  '/broadcasts/$id/': typeof BroadcastsIdIndexRoute
  '/campaigns/$id/': typeof CampaignsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/login'
    | '/broadcasts/$id'
    | '/broadcasts/new'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/broadcasts/'
    | '/campaigns/'
    | '/settings/'
    | '/team/'
    | '/api/automations/enroll'
    | '/api/marketing/send-campaign'
    | '/api/marketing/unsubscribe'
    | '/broadcasts/$id/edit'
    | '/broadcasts/$id/report'
    | '/broadcasts/$id/'
    | '/campaigns/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/login'
    | '/broadcasts/new'
    | '/campaigns/new'
    | '/broadcasts'
    | '/campaigns'
    | '/settings'
    | '/team'
    | '/api/automations/enroll'
    | '/api/marketing/send-campaign'
    | '/api/marketing/unsubscribe'
    | '/broadcasts/$id/edit'
    | '/broadcasts/$id/report'
    | '/broadcasts/$id'
    | '/campaigns/$id'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/login'
    | '/broadcasts/$id'
    | '/broadcasts/new'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/broadcasts/'
    | '/campaigns/'
    | '/settings/'
    | '/team/'
    | '/api/automations/enroll'
    | '/api/marketing/send-campaign'
    | '/api/marketing/unsubscribe'
    | '/broadcasts/$id/edit'
    | '/broadcasts/$id/report'
    | '/broadcasts/$id/'
    | '/campaigns/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  LoginRoute: typeof LoginRoute
  BroadcastsIdRoute: typeof BroadcastsIdRouteWithChildren
  BroadcastsNewRoute: typeof BroadcastsNewRoute
  CampaignsIdRoute: typeof CampaignsIdRouteWithChildren
  CampaignsNewRoute: typeof CampaignsNewRoute
  BroadcastsIndexRoute: typeof BroadcastsIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  ApiAutomationsEnrollRoute: typeof ApiAutomationsEnrollRoute
  ApiMarketingSendCampaignRoute: typeof ApiMarketingSendCampaignRoute
  ApiMarketingUnsubscribeRoute: typeof ApiMarketingUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcasts/': {
      id: '/broadcasts/'
      path: '/broadcasts'
      fullPath: '/broadcasts/'
      preLoaderRoute: typeof BroadcastsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcasts/new': {
      id: '/broadcasts/new'
      path: '/broadcasts/new'
      fullPath: '/broadcasts/new'
      preLoaderRoute: typeof BroadcastsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcasts/$id': {
      id: '/broadcasts/$id'
      path: '/broadcasts/$id'
      fullPath: '/broadcasts/$id'
      preLoaderRoute: typeof BroadcastsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id/': {
      id: '/campaigns/$id/'
      path: '/'
      fullPath: '/campaigns/$id/'
      preLoaderRoute: typeof CampaignsIdIndexRouteImport
      parentRoute: typeof CampaignsIdRoute
    }
    '/broadcasts/$id/': {
      id: '/broadcasts/$id/'
      path: '/'
      fullPath: '/broadcasts/$id/'
      preLoaderRoute: typeof BroadcastsIdIndexRouteImport
      parentRoute: typeof BroadcastsIdRoute
    }
    '/broadcasts/$id/report': {
      id: '/broadcasts/$id/report'
      path: '/report'
      fullPath: '/broadcasts/$id/report'
      preLoaderRoute: typeof BroadcastsIdReportRouteImport
      parentRoute: typeof BroadcastsIdRoute
    }
    '/broadcasts/$id/edit': {
      id: '/broadcasts/$id/edit'
      path: '/edit'
      fullPath: '/broadcasts/$id/edit'
      preLoaderRoute: typeof BroadcastsIdEditRouteImport
      parentRoute: typeof BroadcastsIdRoute
    }
    '/api/marketing/unsubscribe': {
      id: '/api/marketing/unsubscribe'
      path: '/api/marketing/unsubscribe'
      fullPath: '/api/marketing/unsubscribe'
      preLoaderRoute: typeof ApiMarketingUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing/send-campaign': {
      id: '/api/marketing/send-campaign'
      path: '/api/marketing/send-campaign'
      fullPath: '/api/marketing/send-campaign'
      preLoaderRoute: typeof ApiMarketingSendCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automations/enroll': {
      id: '/api/automations/enroll'
      path: '/api/automations/enroll'
      fullPath: '/api/automations/enroll'
      preLoaderRoute: typeof ApiAutomationsEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BroadcastsIdRouteChildren {
  BroadcastsIdEditRoute: typeof BroadcastsIdEditRoute
  BroadcastsIdReportRoute: typeof BroadcastsIdReportRoute
  BroadcastsIdIndexRoute: typeof BroadcastsIdIndexRoute
}

const BroadcastsIdRouteChildren: BroadcastsIdRouteChildren = {
  BroadcastsIdEditRoute: BroadcastsIdEditRoute,
  BroadcastsIdReportRoute: BroadcastsIdReportRoute,
  BroadcastsIdIndexRoute: BroadcastsIdIndexRoute,
}

const BroadcastsIdRouteWithChildren = BroadcastsIdRoute._addFileChildren(
  BroadcastsIdRouteChildren,
)

interface CampaignsIdRouteChildren {
  CampaignsIdIndexRoute: typeof CampaignsIdIndexRoute
}

const CampaignsIdRouteChildren: CampaignsIdRouteChildren = {
  CampaignsIdIndexRoute: CampaignsIdIndexRoute,
}

const CampaignsIdRouteWithChildren = CampaignsIdRoute._addFileChildren(
  CampaignsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  LoginRoute: LoginRoute,
  BroadcastsIdRoute: BroadcastsIdRouteWithChildren,
  BroadcastsNewRoute: BroadcastsNewRoute,
  CampaignsIdRoute: CampaignsIdRouteWithChildren,
  CampaignsNewRoute: CampaignsNewRoute,
  BroadcastsIndexRoute: BroadcastsIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  ApiAutomationsEnrollRoute: ApiAutomationsEnrollRoute,
  ApiMarketingSendCampaignRoute: ApiMarketingSendCampaignRoute,
  ApiMarketingUnsubscribeRoute: ApiMarketingUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
